language: java
jdk:
  - oraclejdk8
script:
  - TERM=dumb
  - gradle check jacocoTestReport
after_success:
  - gradle jacocoRootReport coveralls --info --stacktrace --debug
notifications:
  email: false
